#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - development

before_script:
#  - npm install -g @angular/cli

script:
#  - ng build --prod --aot

after_success:
  - ls -la

#notifications:
#  email:
#    on_failure: change
#    on_success: change