#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - development

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

after_success:
  sshpass -p "$PASS" scp -r $USER@172.104.146.214:/var/www/iservice ./dist

#notifications:
#  email:
#    on_failure: change
#    on_success: change