#.travis.yml

language: node_js
addons:
  apt:
    packages:
    - sshpass
node_js:
  - "6.9"

branches:
  only:
    - development

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

after_success:
  - ls -la ./dist
  - sshpass -p $PASS scp -r ./dist/* $USER@172.104.146.214:/var/www/iservice
  - ls -la ./dist
  - echo $USER
#notifications:
#  email:
#    on_failure: change
#    on_success: change